CREATE USER who IDENTIFIED BY "who123"
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users
PROFILE DEFAULT
ACCOUNT UNLOCK;

-- USER SQL
ALTER USER "WHO"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "WHO" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "DBA" TO "WHO" ;
GRANT "PPLB_ROLE" TO "WHO" ;
GRANT "DV_MONITOR" TO "WHO" ;
GRANT "CTXAPP" TO "WHO" ;
GRANT "DV_AUDIT_CLEANUP" TO "WHO" ;
GRANT "EM_EXPRESS_ALL" TO "WHO" ;
GRANT "WM_ADMIN_ROLE" TO "WHO" ;
GRANT "OLAP_USER" TO "WHO" ;
GRANT "OLAP_XS_ADMIN" TO "WHO" ;
GRANT "DV_SECANALYST" TO "WHO" ;
GRANT "MAINTPLAN_APP" TO "WHO" ;
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO "WHO" ;
GRANT "XS_CACHE_ADMIN" TO "WHO" ;
GRANT "AVTUNE_PKG_ROLE" TO "WHO" ;
GRANT "GDS_CATALOG_SELECT" TO "WHO" ;
GRANT "SCHEDULER_ADMIN" TO "WHO" ;
GRANT "PROVISIONER" TO "WHO" ;
GRANT "AUDIT_ADMIN" TO "WHO" ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "WHO" ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "WHO" ;
GRANT "SYSUMF_ROLE" TO "WHO" ;
GRANT "APPLICATION_TRACE_VIEWER" TO "WHO" ;
GRANT "XDB_WEBSERVICES" TO "WHO" ;
GRANT "LBAC_DBA" TO "WHO" ;
GRANT "OPTIMIZER_PROCESSING_RATE" TO "WHO" ;
GRANT "RECOVERY_CATALOG_USER" TO "WHO" ;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "WHO" ;
GRANT "GSMUSER_ROLE" TO "WHO" ;
GRANT "GATHER_SYSTEM_STATISTICS" TO "WHO" ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "WHO" ;
GRANT "DBJAVASCRIPT" TO "WHO" ;
GRANT "GSM_POOLADMIN_ROLE" TO "WHO" ;
GRANT "DV_ADMIN" TO "WHO" ;
GRANT "DV_POLICY_OWNER" TO "WHO" ;
GRANT "HS_ADMIN_ROLE" TO "WHO" ;
GRANT "XS_SESSION_ADMIN" TO "WHO" ;
GRANT "DV_GOLDENGATE_ADMIN" TO "WHO" ;
GRANT "IMP_FULL_DATABASE" TO "WHO" ;
GRANT "DV_XSTREAM_ADMIN" TO "WHO" ;
GRANT "DV_PATCH_ADMIN" TO "WHO" ;
GRANT "GGSYS_ROLE" TO "WHO" ;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "WHO" ;
GRANT "EJBCLIENT" TO "WHO" ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "WHO" ;
GRANT "JMXSERVER" TO "WHO" ;
GRANT "OLAP_DBA" TO "WHO" ;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "WHO" ;
GRANT "JAVAIDPRIV" TO "WHO" ;
GRANT "SELECT_CATALOG_ROLE" TO "WHO" ;
GRANT "JAVADEBUGPRIV" TO "WHO" ;
GRANT "CONNECT" TO "WHO" ;
GRANT "ACCHK_READ" TO "WHO" ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "WHO" ;
GRANT "SODA_APP" TO "WHO" ;
GRANT "BDSQL_ADMIN" TO "WHO" ;
GRANT "OEM_MONITOR" TO "WHO" ;
GRANT "GSMADMIN_ROLE" TO "WHO" ;
GRANT "AQ_USER_ROLE" TO "WHO" ;
GRANT "JAVAUSERPRIV" TO "WHO" ;
GRANT "XDB_SET_INVOKER" TO "WHO" ;
GRANT "RECOVERY_CATALOG_OWNER" TO "WHO" ;
GRANT "JAVA_ADMIN" TO "WHO" ;
GRANT "DBFS_ROLE" TO "WHO" ;
GRANT "PDB_DBA" TO "WHO" ;
GRANT "RDFCTX_ADMIN" TO "WHO" ;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "WHO" ;
GRANT "CDB_DBA" TO "WHO" ;
GRANT "JAVASYSPRIV" TO "WHO" ;
GRANT "GSMROOTUSER_ROLE" TO "WHO" ;
GRANT "HS_ADMIN_SELECT_ROLE" TO "WHO" ;
GRANT "AUDIT_VIEWER" TO "WHO" ;
GRANT "RESOURCE" TO "WHO" ;
GRANT "DV_OWNER" TO "WHO" ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "WHO" ;
GRANT "EXECUTE_CATALOG_ROLE" TO "WHO" ;
GRANT "DATAPATCH_ROLE" TO "WHO" ;
GRANT "DV_ACCTMGR" TO "WHO" ;
GRANT "EXP_FULL_DATABASE" TO "WHO" ;
GRANT "DBMS_MDX_INTERNAL" TO "WHO" ;
GRANT "DV_STREAMS_ADMIN" TO "WHO" ;
GRANT "XS_NAMESPACE_ADMIN" TO "WHO" ;
GRANT "BDSQL_USER" TO "WHO" ;
GRANT "ORDADMIN" TO "WHO" ;
GRANT "AUTHENTICATEDUSER" TO "WHO" ;
GRANT "CAPTURE_ADMIN" TO "WHO" ;
GRANT "OEM_ADVISOR" TO "WHO" ;
GRANT "XS_CONNECT" TO "WHO" ;
GRANT "XDBADMIN" TO "WHO" ;
GRANT "EM_EXPRESS_BASIC" TO "WHO" ;
ALTER USER "WHO" DEFAULT ROLE "DBA","PPLB_ROLE","DV_MONITOR","CTXAPP","DV_AUDIT_CLEANUP","EM_EXPRESS_ALL","WM_ADMIN_ROLE","OLAP_USER","OLAP_XS_ADMIN","DV_SECANALYST","MAINTPLAN_APP","RECOVERY_CATALOG_OWNER_VPD","XS_CACHE_ADMIN","AVTUNE_PKG_ROLE","GDS_CATALOG_SELECT","SCHEDULER_ADMIN","PROVISIONER","AUDIT_ADMIN","XDB_WEBSERVICES_OVER_HTTP","AQ_ADMINISTRATOR_ROLE","SYSUMF_ROLE","APPLICATION_TRACE_VIEWER","XDB_WEBSERVICES","LBAC_DBA","OPTIMIZER_PROCESSING_RATE","RECOVERY_CATALOG_USER","DV_DATAPUMP_NETWORK_LINK","GSMUSER_ROLE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","DBJAVASCRIPT","GSM_POOLADMIN_ROLE","DV_ADMIN","DV_POLICY_OWNER","HS_ADMIN_ROLE","XS_SESSION_ADMIN","DV_GOLDENGATE_ADMIN","IMP_FULL_DATABASE","DV_XSTREAM_ADMIN","DV_PATCH_ADMIN","GGSYS_ROLE","DATAPUMP_EXP_FULL_DATABASE","EJBCLIENT","HS_ADMIN_EXECUTE_ROLE","JMXSERVER","OLAP_DBA","ADM_PARALLEL_EXECUTE_TASK","JAVAIDPRIV","SELECT_CATALOG_ROLE","JAVADEBUGPRIV","CONNECT","ACCHK_READ","DATAPUMP_IMP_FULL_DATABASE","SODA_APP","BDSQL_ADMIN","OEM_MONITOR","GSMADMIN_ROLE","AQ_USER_ROLE","JAVAUSERPRIV","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","JAVA_ADMIN","DBFS_ROLE","PDB_DBA","RDFCTX_ADMIN","DV_GOLDENGATE_REDO_ACCESS","CDB_DBA","JAVASYSPRIV","GSMROOTUSER_ROLE","HS_ADMIN_SELECT_ROLE","AUDIT_VIEWER","RESOURCE","DV_OWNER","XDB_WEBSERVICES_WITH_PUBLIC","EXECUTE_CATALOG_ROLE","DATAPATCH_ROLE","DV_ACCTMGR","EXP_FULL_DATABASE","DBMS_MDX_INTERNAL","DV_STREAMS_ADMIN","XS_NAMESPACE_ADMIN","BDSQL_USER","ORDADMIN","AUTHENTICATEDUSER","CAPTURE_ADMIN","OEM_ADVISOR","XS_CONNECT","XDBADMIN","EM_EXPRESS_BASIC";

-- SYSTEM PRIVILEGES